name: futbol_pro
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  # Aseguramos que se usa Flutter/Dart 3.x
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  
  # ----------------------------------------
  # GESTIÓN DE ESTADO Y ARQUITECTURA
  # ----------------------------------------
  flutter_bloc: ^8.1.5 # Versión actualizada
  equatable: ^2.0.5 
  dartz: ^0.10.1
  get_it: ^7.7.0
  
  # ----------------------------------------
  # NAVEGACIÓN
  # ----------------------------------------
  go_router: ^14.0.0 # Manteniendo tu restricción de versión, aunque la más nueva es 16.x
  
  # ----------------------------------------
  # SERVICIOS (VERSIONES CRÍTICAS ACTUALIZADAS)
  # ----------------------------------------
  http: ^1.2.1 
  firebase_core: ^2.27.0 # <--- ¡ACTUALIZADO!
  firebase_messaging: ^14.8.10 # <--- ¡ACTUALIZADO!
  intl: ^0.19.0 # Versión compatible con Flutter 3.x
  cloud_firestore: ^4.17.5
  image_picker: ^1.2.0
  firebase_storage: ^11.7.7
  flutter_local_notifications: ^19.5.0
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0 # Versión compatible con Flutter 3.x

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
