// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvXQdGcTtFmU979XPFkdLo5Mzl4Tbey58',
    appId: '1:1011658046972:web:d3470397c04283c9a2c679',
    messagingSenderId: '1011658046972',
    projectId: 'masai-app',
    authDomain: 'masai-app.firebaseapp.com',
    storageBucket: 'masai-app.firebasestorage.app',
    measurementId: 'G-JG1SZ1K0FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRTB9kQvwRgMb6I6C_XW_uRSE8xvaUukU',
    appId: '1:1011658046972:android:5a53a1c7bdf372d5a2c679',
    messagingSenderId: '1011658046972',
    projectId: 'masai-app',
    storageBucket: 'masai-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_n8wfDNGXRX2WljUoS229wcoWr3_YyWc',
    appId: '1:1011658046972:ios:a4d53e3a57475d9aa2c679',
    messagingSenderId: '1011658046972',
    projectId: 'masai-app',
    storageBucket: 'masai-app.firebasestorage.app',
    iosBundleId: 'com.example.futbolPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_n8wfDNGXRX2WljUoS229wcoWr3_YyWc',
    appId: '1:1011658046972:ios:a4d53e3a57475d9aa2c679',
    messagingSenderId: '1011658046972',
    projectId: 'masai-app',
    storageBucket: 'masai-app.firebasestorage.app',
    iosBundleId: 'com.example.futbolPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvXQdGcTtFmU979XPFkdLo5Mzl4Tbey58',
    appId: '1:1011658046972:web:5c49f749c56ecf4da2c679',
    messagingSenderId: '1011658046972',
    projectId: 'masai-app',
    authDomain: 'masai-app.firebaseapp.com',
    storageBucket: 'masai-app.firebasestorage.app',
    measurementId: 'G-KMV86H0CBN',
  );
}
